import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { SessionProviderWrapper } from "@/provider";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <SessionProviderWrapper>
            <NextTopLoader
            color="#FF8022"
            showSpinner={false}
            crawl={false}
            />
            {children}
            <ToastContainer/>
          </SessionProviderWrapper>
        </body>

    </html>
  );
}
